openapi: 3.1.0
info:
  title: Control Points API
  version: 1.0.0

paths:
  /control-points:
    get:
      description: Get all Control Points
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ControlPoint"
        400:
          $ref: "./common.yaml#/components/responses/BadRequest"
        401:
          $ref: "./common.yaml#/components/responses/Unauthorized"
        403:
          $ref: "./common.yaml#/components/responses/Forbidden"

components:
  schemas:
    ControlPoint:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier of the Control Point
        organisationId:
          type: integer
          description: Identifier for the organisation managing the Control Point
        name:
          type: string
          description: Name of the Control Point
        code:
          type: string
          description: Code assigned to the Control Point
