openapi: 3.1.0
info:
  title: Control Points API
  version: 1.0.0

paths:
  /control-points:
    get:
      description: Get all Control Points
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ControlPoint"
        400:
          $ref: "./common.yaml#/components/responses/BadRequest"
        401:
          $ref: "./common.yaml#/components/responses/Unauthorized"
        403:
          $ref: "./common.yaml#/components/responses/Forbidden"
  /control-points/{id}:
    get:
      description: Get Control Point by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            $ref: "#/components/schemas/Id"
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ControlPoint"
        400:
          $ref: "./common.yaml#/components/responses/BadRequest"
        401:
          $ref: "./common.yaml#/components/responses/Unauthorized"
        403:
          $ref: "./common.yaml#/components/responses/Forbidden"
        404:
          $ref: "./common.yaml#/components/responses/NotFound"

components:
  schemas:
    Id:
      type: integer
      description: Unique identifier of the Control Point
    ControlPoint:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Id"
        organisationId:
          type: integer
          description: Identifier for the organisation managing the Control Point
        name:
          type: string
          description: Name of the Control Point
        code:
          type: string
          description: Code assigned to the Control Point
